/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiSettingsRouteImport } from './routes/api-settings'
import { Route as IndexRouteImport } from './routes/index'

const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api-settings',
  path: '/api-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-settings': typeof ApiSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-settings': typeof ApiSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-settings': typeof ApiSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api-settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-settings'
  id: '__root__' | '/' | '/api-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api-settings': {
      id: '/api-settings'
      path: '/api-settings'
      fullPath: '/api-settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSettingsRoute: ApiSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
